services:
  db:
    image: pgvector/pgvector:0.8.0-pg16
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smartclm-poc
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smartclm-poc -h localhost"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 10s

  api:
    image: 026090544348.dkr.ecr.ap-northeast-2.amazonaws.com/smartclm-dev/api:latest
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      uv run gunicorn src.main:app 
      -w 1 
      -k uvicorn.workers.UvicornWorker 
      --bind 0.0.0.0:8000 
      --timeout 600
    depends_on:
      db:
        condition: service_healthy
      doc-converter:
        condition: service_started
      doc-parser:
        condition: service_started
    restart: unless-stopped

  doc-converter:
    image: 026090544348.dkr.ecr.ap-northeast-2.amazonaws.com/smartclm-dev/doc-converter:latest
    container_name: doc-converter
    ports:
      - "8001:8001"
    restart: unless-stopped

  doc-parser:
    image: 026090544348.dkr.ecr.ap-northeast-2.amazonaws.com/smartclm-dev/doc-parser:latest
    container_name: doc-parser
    ports:
      - "8002:8002"
    restart: unless-stopped

volumes:
  pgdata:
